spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://47.94.96.2:3301/nmxpps?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: nmxpps
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    slave:
      jdbc-url: jdbc:mysql://47.94.96.2:3302/nmxpps?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: nmxpps
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes: 172.24.48.132:6379,172.24.48.132:6380,172.24.48.132:6381,172.24.48.132:6382,172.24.48.132:6383,172.24.48.132:6384
mybatis-plus:
  mapper-locations: classpath:/mybatis-plus/*.xml
  configuration:
    call-setters-on-nulls: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
