spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://172.17.0.5:3301/nmxpps?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: nmxpps
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    slave:
      jdbc-url: jdbc:mysql://172.17.0.5:3302/nmxpps?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: nmxpps
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes: 47.94.96.2:6379,47.94.96.2:6380,47.94.96.2:6381,47.94.96.2:6382,47.94.96.2:6383,47.94.96.2:6384
mybatis-plus:
  mapper-locations: classpath:/mybatis-plus/*.xml
  configuration:
    call-setters-on-nulls: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
